<?php

return [
    'guarderia' => [
        'title' => 'Guardería educativa',
        'eyebrow' => 'Primeros aprendizajes',
        'description' => 'Un entorno cuidado donde cada actividad acompaña el desarrollo, la autonomía y la curiosidad de los más pequeños.',
        'topics' => ['Estimulación temprana', 'Motricidad', 'Lenguaje', 'Hábitos y autonomía'],
    ],
    'inicial' => [
        'title' => 'Nivel inicial',
        'eyebrow' => 'Aprender jugando',
        'description' => 'Acompañamiento personalizado para fortalecer las bases de lectura, escritura, lógica y expresión.',
        'topics' => ['Prelectura', 'Pensamiento lógico', 'Expresión oral', 'Creatividad'],
    ],
    'primaria' => [
        'title' => 'Apoyo para primaria',
        'eyebrow' => 'Bases sólidas',
        'description' => 'Refuerzo escolar cercano y claro para comprender mejor, ganar confianza y avanzar en cada materia.',
        'topics' => ['Matemática', 'Lenguaje', 'Ciencias', 'Técnicas de estudio'],
    ],
    'secundaria' => [
        'title' => 'Apoyo para secundaria',
        'eyebrow' => 'Comprender para avanzar',
        'description' => 'Clases enfocadas en resolver dudas, consolidar contenidos y mejorar el desempeño académico.',
        'topics' => ['Matemática', 'Física', 'Química', 'Lenguaje'],
    ],
    'preuniversitario' => [
        'title' => 'Preparación preuniversitaria',
        'eyebrow' => 'Tu siguiente etapa',
        'description' => 'Preparación estratégica para exámenes de ingreso, con práctica guiada y seguimiento constante.',
        'topics' => ['Simulacros', 'Razonamiento', 'Resolución de problemas', 'Plan de estudio'],
    ],
    'universitario' => [
        'title' => 'Apoyo universitario',
        'eyebrow' => 'Domina materias exigentes',
        'description' => 'Tutorías personalizadas para comprender contenidos complejos y avanzar con una metodología clara.',
        'topics' => ['Cálculo', 'Álgebra', 'Física', 'Estadística'],
    ],
    'computacion' => [
        'title' => 'Computación',
        'eyebrow' => 'Competencias digitales',
        'description' => 'Formación práctica para usar herramientas digitales con seguridad, criterio y autonomía.',
        'topics' => ['Ofimática', 'Internet', 'Productividad', 'Herramientas digitales'],
    ],
    'programacion' => [
        'title' => 'Programación',
        'eyebrow' => 'Crea con tecnología',
        'description' => 'Aprende lógica, algoritmos y desarrollo de proyectos mediante experiencias prácticas.',
        'topics' => ['Lógica', 'Web', 'Aplicaciones', 'Proyectos'],
    ],
    'robotica' => [
        'title' => 'Robótica',
        'eyebrow' => 'Ingenio en movimiento',
        'description' => 'Diseña, construye y programa soluciones mientras desarrollas pensamiento lógico y creatividad.',
        'topics' => ['Electrónica', 'Programación', 'Prototipado', 'Resolución de retos'],
    ],
    'creacionapp' => [
        'title' => 'Creación de aplicaciones',
        'eyebrow' => 'De la idea al producto',
        'description' => 'Convierte una idea en una aplicación funcional mediante un proceso práctico y ordenado.',
        'topics' => ['Diseño de interfaz', 'Desarrollo', 'Pruebas', 'Publicación'],
    ],
    'disenoweb' => [
        'title' => 'Diseño web',
        'eyebrow' => 'Experiencias digitales',
        'description' => 'Crea sitios modernos, accesibles y adaptables con fundamentos sólidos de diseño y desarrollo.',
        'topics' => ['HTML y CSS', 'Responsive', 'UX/UI', 'Publicación web'],
    ],
    'disenografico' => [
        'title' => 'Diseño gráfico',
        'eyebrow' => 'Comunicación visual',
        'description' => 'Desarrolla criterio visual y domina herramientas para crear piezas claras y profesionales.',
        'topics' => ['Composición', 'Color', 'Tipografía', 'Identidad visual'],
    ],
    'mantenimientocomputadoras' => [
        'title' => 'Mantenimiento de computadoras',
        'eyebrow' => 'Tecnología que funciona',
        'description' => 'Aprende diagnóstico, mantenimiento preventivo y solución de problemas frecuentes.',
        'topics' => ['Hardware', 'Software', 'Diagnóstico', 'Mantenimiento'],
    ],
    'ajedrez' => [
        'title' => 'Ajedrez',
        'eyebrow' => 'Estrategia y concentración',
        'description' => 'Entrena planificación, memoria y toma de decisiones a través del juego ciencia.',
        'topics' => ['Fundamentos', 'Táctica', 'Estrategia', 'Práctica guiada'],
    ],
    'cuborubik' => [
        'title' => 'Cubo Rubik',
        'eyebrow' => 'Lógica en tus manos',
        'description' => 'Aprende métodos de resolución y fortalece memoria, paciencia y visión espacial.',
        'topics' => ['Método por capas', 'Algoritmos', 'Velocidad', 'Memoria visual'],
    ],
    'fotocopia' => [
        'title' => 'Impresión y fotocopias',
        'eyebrow' => 'Soluciones rápidas',
        'description' => 'Servicios de impresión y apoyo documental para estudiantes, familias y profesionales.',
        'topics' => ['Impresión', 'Fotocopias', 'Digitalización', 'Documentos'],
    ],
    'resolucionpracticos' => [
        'title' => 'Resolución de prácticos',
        'eyebrow' => 'Acompañamiento académico',
        'description' => 'Orientación paso a paso para comprender consignas y resolver ejercicios con criterio propio.',
        'topics' => ['Interpretación', 'Procedimientos', 'Revisión', 'Explicación personalizada'],
    ],
    'asistenteife' => [
        'title' => 'Asistente IFE',
        'eyebrow' => 'Apoyo con inteligencia artificial',
        'description' => 'Una herramienta complementaria para consultar, practicar y organizar tu aprendizaje.',
        'topics' => ['Consultas', 'Práctica', 'Organización', 'Aprendizaje asistido'],
    ],
    'matematica' => ['title' => 'Matemática', 'eyebrow' => 'Razonamiento claro', 'description' => 'Comprende conceptos, practica procedimientos y resuelve problemas con seguridad.', 'topics' => ['Aritmética', 'Geometría', 'Funciones', 'Problemas']],
    'fisica' => ['title' => 'Física', 'eyebrow' => 'Comprende el mundo', 'description' => 'Aprende física conectando conceptos, fórmulas y situaciones reales.', 'topics' => ['Mecánica', 'Energía', 'Electricidad', 'Problemas']],
    'quimica' => ['title' => 'Química', 'eyebrow' => 'Ciencia paso a paso', 'description' => 'Domina conceptos y cálculos químicos mediante explicaciones claras y práctica guiada.', 'topics' => ['Materia', 'Reacciones', 'Estequiometría', 'Química orgánica']],
    'algebra' => ['title' => 'Álgebra', 'eyebrow' => 'Estructura y lógica', 'description' => 'Fortalece el pensamiento algebraico y resuelve expresiones y ecuaciones con método.', 'topics' => ['Expresiones', 'Ecuaciones', 'Sistemas', 'Factorización']],
    'lenguaje' => ['title' => 'Lenguaje', 'eyebrow' => 'Comunica mejor', 'description' => 'Mejora comprensión, redacción, ortografía y capacidad de argumentación.', 'topics' => ['Lectura', 'Redacción', 'Ortografía', 'Expresión oral']],
    'ingles' => ['title' => 'Inglés', 'eyebrow' => 'Nuevas oportunidades', 'description' => 'Aprende inglés de forma progresiva con práctica útil y acompañamiento cercano.', 'topics' => ['Vocabulario', 'Gramática', 'Conversación', 'Comprensión']],
    'estadistica' => ['title' => 'Estadística', 'eyebrow' => 'Datos con sentido', 'description' => 'Interpreta información, aplica métodos estadísticos y comunica resultados con claridad.', 'topics' => ['Descriptiva', 'Probabilidad', 'Inferencia', 'Gráficos']],
    'planescorporativos' => ['title' => 'Planes corporativos', 'eyebrow' => 'Formación para equipos', 'description' => 'Programas adaptados a organizaciones que buscan fortalecer competencias concretas.', 'topics' => ['Diagnóstico', 'Plan personalizado', 'Capacitación', 'Seguimiento']],
];
